"""Add parent_id to Comment and CommentLike table

Revision ID: d77e51a48f54
Revises: f73eddd18bbd
Create Date: 2025-07-13 15:27:27.425596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77e51a48f54'
down_revision = 'f73eddd18bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comment_parent_id_comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_parent_id_comment', type_='foreignkey')
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###
