"""init all scientific profile fields

Revision ID: fb7579964bba
Revises: 
Create Date: 2025-07-10 14:43:18.217906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7579964bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('degree', sa.String(length=64), nullable=True),
    sa.Column('interests', sa.String(length=256), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('scholar_links', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('birthdate', sa.String(length=32), nullable=True),
    sa.Column('public_email', sa.String(length=120), nullable=True),
    sa.Column('telegram', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
