"""initial migration for all models

Revision ID: 506e23e8356d
Revises: 1c08f917242c
Create Date: 2025-07-14 19:51:09.285055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506e23e8356d'
down_revision = '1c08f917242c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('show_status', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('show_bio', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('show_full_name', sa.Boolean(), nullable=True),
    sa.Column('degree', sa.String(length=64), nullable=True),
    sa.Column('show_degree', sa.Boolean(), nullable=True),
    sa.Column('interests', sa.String(length=256), nullable=True),
    sa.Column('show_interests', sa.Boolean(), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('show_organization', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('show_location', sa.Boolean(), nullable=True),
    sa.Column('scholar_links', sa.String(length=512), nullable=True),
    sa.Column('show_scholar_links', sa.Boolean(), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('show_website', sa.Boolean(), nullable=True),
    sa.Column('birthdate', sa.String(length=32), nullable=True),
    sa.Column('show_birthdate', sa.Boolean(), nullable=True),
    sa.Column('public_email', sa.String(length=120), nullable=True),
    sa.Column('show_public_email', sa.Boolean(), nullable=True),
    sa.Column('telegram', sa.String(length=64), nullable=True),
    sa.Column('show_telegram', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('comment_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_like')
    op.drop_table('post_tags')
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('follows')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
