"""Add extended models for WorkNest platform

Revision ID: e422b3dda581
Revises: 506e23e8356d
Create Date: 2025-07-14 21:56:08.045195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e422b3dda581'
down_revision = '506e23e8356d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_comment_article_id', 'article', ['article_id'], ['id'])

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=True))
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_like_article_id', 'article', ['article_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('publish_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('post_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preview_text', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_post_category_id', 'category', ['category_id'], ['id'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ban_until', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('ban_until')
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')
        batch_op.drop_column('role')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('color')
        batch_op.drop_column('description')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('preview_text')
        batch_op.drop_column('attachments')
        batch_op.drop_column('edit_count')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('post_type')
        batch_op.drop_column('publish_at')
        batch_op.drop_column('is_published')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('category_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('article_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('article_id')

    # ### end Alembic commands ###
